import ArkLib.ToMathlib.BridgeListDecodingCA
import ArkLib.ToMathlib.Bridge2GCXK25
import ArkLib.ToMathlib.Bridge2BCHKS25
import ArkLib.ToMathlib.Bridge2BGKS20

-- Bridge2GCXK25
#print axioms ProximityGap.mcaBad_subset_biUnion_mcaBadWitness
#print axioms ProximityGap.mcaBad_card_le_sum_mcaBadWitness_card
#print axioms ProximityGap.mcaBad_card_le_of_per_codeword

-- BridgeListDecodingCA (GCXK25 additions)
#print axioms CodingTheory.Bridge.mcaBad_card_le_listFactor_mul_perCodeword
#print axioms CodingTheory.Bridge.epsMCA_le_ofReal_of_per_codeword_count
#print axioms CodingTheory.Bridge.mcaEvent_prob_le_ofReal_of_per_codeword_count

-- Bridge2BCHKS25
#print axioms CodingTheory.Bridge.ofReal_le_card_div_of_card_mul_le
#print axioms CodingTheory.Bridge.epsCA_ge_inv_of_badLineWitness
#print axioms CodingTheory.Bridge.epsCA_ge_half_inv_n_of_badLineWitness
#print axioms CodingTheory.Bridge.epsCA_badLine_bridge_of_residual
#print axioms CodingTheory.Bridge.hBadLine_of_provBadLine

-- Bridge2BGKS20
#print axioms CodingTheory.Bridge.ofReal_one_sub_inv_le_card_div
#print axioms CodingTheory.Bridge.epsCA_ge_one_sub_inv_of_nearCertainWitness
#print axioms CodingTheory.Bridge.epsCA_separation_bridge_of_residual
