/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/

import ArkLib.AGM.Basic

/-!
# Foundational lemmas on AGM group representations

Companion lemmas to `ArkLib/AGM/Basic.lean`'s `GroupRepresentation` (the algebraic-adversary
representation: a target group element together with an exponent vector over a basis of
previously-seen elements).  `Basic.lean` proves *soundness* (`target_mem_closure`: a represented
target lies in the subgroup generated by the basis) and *functoriality* (`map`: a group hom
transports a representation, preserving exponents).  This file adds the matching structural facts:

* `target_eq_of_exponents_eq` — **determinism**: the target is fully determined by the basis and
  the exponent vector (the functional converse of soundness).
* `map_exponents` — functoriality acts only on the basis, leaving the exponent vector fixed.
* `singleton_target_mem_zpowers` — the rank-1 target `g ^ a.val` lies in `Subgroup.zpowers g`.
-/

namespace AGM.GroupRepresentation

variable {G : Type*} [Group G] {p : ℕ}

/-- **Representation determinism.** The target of an algebraic representation is fully determined
by its basis and exponent vector: two representations over the same basis carrying the same
exponents represent the same group element. The functional counterpart to `target_mem_closure`
(soundness): basis + exponents determine a unique target. -/
theorem target_eq_of_exponents_eq {prev : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev t₁) (r₂ : GroupRepresentation (p := p) prev t₂)
    (h : r₁.exponents = r₂.exponents) : t₁ = t₂ := by
  rw [← r₁.hEq, ← r₂.hEq, h]

/-- Functoriality acts only on the basis: transporting a representation along a group hom `f`
(`GroupRepresentation.map`) leaves the exponent vector unchanged. -/
@[simp] theorem map_exponents {H : Type*} [Group H] (f : G →* H) {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    (repr.map f).exponents = repr.exponents := rfl

/-- The rank-1 target `g ^ a.val` lies in the cyclic subgroup generated by `g`. -/
theorem singleton_target_mem_zpowers (g : G) (a : ZMod p) :
    g ^ a.val ∈ Subgroup.zpowers g :=
  pow_mem (Subgroup.mem_zpowers g) a.val

end AGM.GroupRepresentation
