/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.AdditiveEnergyRepBound
import Mathlib.Data.ZMod.Basic
import Mathlib.Tactic

/-!
# A finite-field minimal-energy witness: `E(μ_8 ⊂ F₇₃) = 168` (#389)

`SidonModNegComplex.lean` proves the char-0 minimal additive energy `E(μ_n) = 3n²−3n` for
every set of roots of unity in `ℂ`, with no threshold.  Over `F_p` the minimality is
genuinely prime-arithmetic: it can hold or fail at the same subgroup order depending on the
prime (`E(μ_16 ⊂ F₂₅₇) = 912 > 720`, not minimal, even though `16 < √257`).

This file lands the first **finite-field minimal-energy value beyond the fleet's order-4
`H4`** — the order-8 subgroup of `F₇₃`:

> **`energy_mu8_F73`** — `E(μ_8 ⊂ F₇₃) = 168 = 3·8² − 3·8`, the minimal (char-0) value,
> realized over a finite field in the deployed `n ≪ √p` regime (`8 < √73 ≈ 8.5`).
> Proved by direct `decide` on the additive-energy *count* (the nested-`∀` `SidonModNeg`
> predicate is `decide`-infeasible at `n = 8` over `ZMod 73`; the energy sum is not).

So the char-0 minimality (proven with no threshold over `ℂ`) does lift to a concrete
production-shape `F_p` point — but only at *some* primes, confirming the lift is the
Mann–Conway–Jones height phenomenon, not a clean `n < c√p` law (probe `O160`).  This is a
machine-checked data point on the Johnson-side energy chain, not a crossing of the
past-Johnson wall.  Issue #389.
-/

open ArkLib.ProximityGap.AdditiveEnergyRepBound

namespace ArkLib.ProximityGap.EnergyMinimalF73

local instance : Fact (Nat.Prime 73) := ⟨by norm_num⟩

/-- The order-8 multiplicative subgroup `μ_8 ⊂ F₇₃` (generated by `10`). -/
def mu8 : Finset (ZMod 73) := {1, 10, 22, 27, 46, 51, 63, 72}

set_option maxHeartbeats 4000000 in
/-- **`E(μ_8 ⊂ F₇₃) = 168`** — the minimal char-0 additive energy `3·8² − 3·8`, realized
over a finite field, by direct computation of the additive-energy count. -/
theorem energy_mu8_F73 : additiveEnergy mu8 = 168 := by decide

end ArkLib.ProximityGap.EnergyMinimalF73

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ArkLib.ProximityGap.EnergyMinimalF73.energy_mu8_F73
